### PR TITLE
Changing the file structure to use composer and auto-loading

### PR DESCRIPTION
**Pull request by awjudd**
* Moved the Resource classes into the "src" directory
* Removed the hard dependency on having a password for your database
* Added in a dependency on phpdotenv - the install script should write a .env file outside of web root instead of the config.php

### CODE REVIEW

**Comment by awjudd** [comment]
Please Note: I haven't tested the full site with these changes.  There may be issues as a result of this change.

**Comment by Dinocanid** [comment]
A few things before I merge it:

- bootstrap.php is not needed, since it's loaded in via a link from the CDN in the header.tpl file of whatever theme it's used for ("script src and link rel"). No need to include it as it's own file if every theme won't use it.
- .htaccess already exists, github just doesn't like .htaccess files for security reasons, which is why the current ones are in ZIPs. (This is just for the repo's sake, in releases they'll be unzipped of course)
- Shouldn't the domain, by default, remain localhost/127.0.0.1? When used with WAMPP/XAMPP this is what it would be anyway, and when installing on a server the domain is set to whatever it was set as during installation
- For security reasons, shouldn't configwrite.php still check for the password? Having your database password-protected seems like best practice.

**Comment by awjudd** [comment]
- `bootstrap.php` has nothing to do with Twitter Bootstrap and everything to do with bootstrapping (i.e. setting up/initializing the website)
- GitHub has no issue with `.htaccess` files, otherwise I wouldn't have been able to upload it.  There is no need to zip it.
- I'm not sure what you mean by 3
- It should not prevent me from installing the app should I choose to use insecure practices.  This is more important on a development machine because the database server is locked down to my computer the fact that I needed to make a user just to test the installation process was silly.  Maybe instead later on you can add a "I understand that this is a security concern, let me do it anyway button" so then you are at least able to still install.

**Comment by Dinocanid** [comment]
- I tried multiple times to upload a .htaccess file to the repo and it was always rejected due to security concerns. Maybe it was only for web-based uploading though, I haven't tried uploading the .htaccess through the desktop.
- In config.php you changed the domain to "mysidia.dev"
- The precaution is in place for sites being hosted online and not locally, but I'll work on making it possible to proceed without it (accompanied by a warning), to make things easier for those who do local testing.

**Comment by awjudd** [comment]
Honestly, the `config.php` file should not be included in source control (i.e. ignored by the `.gitignore` file).  That was my local settings that were committed - I did remove that and re-committed.

**Pull request merged**
